language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      oracle-java8-installer # Updates JDK 8 to the latest available.


after_success:
- bash <(curl -s https://codecov.io/bash)